name: 'Sync GitHub Advanced Security and Asana'
description: "This helps sync GHAS alerts to ASANA by creating an
              issue for each alert."
inputs:
  asana_url:
    description: 'URL of the asana instance'
    required: true
  asana_token:
    description: 'asana password or token'
    required: true
  asana_workspace:
    description: 'asana workspace id'
    required: true
  asana_project:
    description: 'asana project id'
    required: true
  github_token:
    description: 'GitHub API token with the required permissions'
    required: false
    default: ${{ github.token }}
  sync_direction:
    description: 'Which direction to synchronize in ("gh2asana")'
    required: false
    default: 'gh2asana'
runs:
  using: composite
  steps:
  - name: Run GitHub to asana Sync
    working-directory: ${{ github.action_path }}
    shell: bash
    env:
      INPUTS_GITHUB_TOKEN: ${{ inputs.github_token }}
      INPUTS_ASANA_URL: ${{ inputs.asana_url }}
      INPUTS_ASANA_TOKEN: ${{ inputs.asana_token }}
      INPUTS_ASANA_WORKSPACE: ${{ inputs.asana_workspace }}
      INPUTS_ASANA_PROJECT: ${{ inputs.asana_project }}
      INPUTS_SYNC_DIRECTION: ${{ inputs.sync_direction }}
    run: |
      pip3 install -r requirements.txt
      REPOSITORY_NAME="$(echo "$GITHUB_REPOSITORY" | cut -d/ -f 2)"
      ./gh2asana sync \
        --gh-url "$GITHUB_API_URL" \
        --gh-token "$INPUTS_GITHUB_TOKEN" \
        --gh-org "$GITHUB_REPOSITORY_OWNER" \
        --gh-repo "$REPOSITORY_NAME" \
        --asana-url "$INPUTS_ASANA_URL" \
        --asana-token "$INPUTS_ASANA_TOKEN" \
        --asana-workspace "$INPUTS_ASANA_WORKSPACE" \
        --asana-project "$INPUTS_ASANA_PROJECT" \
        --direction "$INPUTS_SYNC_DIRECTION" \
