name: Asana Create Ticket

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Asana Task
        uses: honeycombio/gha-create-asana-task@main
        with:
          asana-secret: ${{ secrets.ASANA_PAT }}
          asana-workspace-id: ${{ secrets.ASANA_WORKSPACE_ID }}
          asana-project-id: ${{ secrets.ASANA_PROJECT_ID }}
          asana-section-id: ${{ secrets.ASANA_SECTION_ID }}
          asana-task-name: My Asana Task
