name: "GitHub to Jira"

on: workflow_dispatch

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Sync alerts to Jira issues
        uses: github/ghas-jira-integration@v1
        with:
          jira_url: 'https://githubtraining.atlassian.net/'
          jira_user: '${{ secrets.JIRA_USERNAME }}'
          jira_token: '${{ secrets.JIRA_TOKEN }}'
          jira_project: 'EJ'
          github_token: ${{ github.token }}
          sync_direction: 'gh2jira'
