name: GitHub to Asana

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1
      - name: Create Asana Task
        uses: ./
        with:
          asana-url: https://app.asana.com/api/1.0
          asana-token: ${{ secrets.ASANA_PAT }}
          asana-workspace: ${{ secrets.ASANA_WORKSPACE_ID }}
          asana-project: ${{ secrets.ASANA_PROJECT_ID }}
